package br.gov.ce.fortaleza.sepog.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@XmlRootElement
public class IssueChamadoKSPessoa  {

	//@org.kie.api.definition.type.Label(value = "name")
	private String name;
	//@org.kie.api.definition.type.Label(value = "idade")
	private String idade;

	public IssueChamadoKSPessoa() {
	}
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getIdade() {
		return this.idade;
	}

	public void setIdade(String idade) {
		this.idade = idade;
	}

	public IssueChamadoKSPessoa(String name, String idade) {
		this.name = name;
		this.idade = idade;
	}

}